### ISSUE TITLE
missing type int64

### ISSUE THREAD

**Issue by miambe** [bitfocus/companion-module-generic-emberplus#5]
I successfully use the emberplus-console software to trigger a fader on my DHD.AUDIO console.
Here is the command line used :
EmberPlus-Console -w -n 172.30.22.3 "0.3.231.2/:1000"   
EmberPlus-Console is available on [https://github.com/LeeO86/EmberPlus-Console](https://github.com/LeeO86/EmberPlus-Console)

If I check with Ember+ viewer, I can see the type is int64 and not int
![image](https://user-images.githubusercontent.com/28531818/150154212-b245985d-40dc-41df-ae9e-f83407ce7b21.png)
As there is no integer64 option in Companion, I use "ember plus generic Set Value Integer"
![image](https://user-images.githubusercontent.com/28531818/150158633-e4f34d86-ba59-4014-8145-d213a81c22c3.png)
And I'm getting this warning on log :
![image](https://user-images.githubusercontent.com/28531818/150156361-6152a293-7110-45aa-8c53-1f7b85f4179c.png)
Same issue if I use "ember plus generic Set Value String"
Could you implement int64 and allow minus values?
As you can see, the fader accept a value between -16000 and 1000

Olivier

**Comment by krocheck** [comment]
@baltedewit will need to weigh in when available.  I did some poking first in the [upstream library](https://github.com/nrkno/sofie-emberplus-connection/blob/7328b284f4c7ab7057c3c06aa18c83db69bcfeea/src/model/Parameter.ts#L7) which does not provide a distinction between Int and Int64.  So I checked the [original Ember+ library](https://github.com/Lawo/ember-plus/blob/3a4c4ab312bea08c45bc2707c157720ca801f7d0/tinyember/TinyEmberPlus/glow/util/ParameterConverter.cpp#L11) as well which doesn't seem to make that distinction either.  And I would say its rather odd to use `int64` for a range only requiring -16000 - 1000 as that fits easily into a standard `int` range of +/-32,768.  So there might be something else going wrong here then a type not being supported.

**Comment by baltedewit** [comment]
The specific warning you get is a bug that prevents the module from setting integers. It has been fixed in v1.1.2 of the module, I have asked companion maintainers to upgrade but it looks like that hasn't happened yet. @krocheck perhaps you can make this happen?

**Comment by krocheck** [comment]
Yeah, musta got lost in the shuffle.  Done.  Sorry

**Comment by miambe** [comment]
@baltedewit Thanks for the quick reply!!!
@krocheck So I will wait companion-2.1.5-XXX-win64.exe and confirms.

**Comment by krocheck** [comment]
It is going into the latest beta, which you can download from the "Beta Builds" area of the Bitfocus website where you download Companion.  If you want it in a stable release, you'll have to wait for v2.2.0

**Comment by miambe** [comment]
@krocheck I've installed the beta 2.2.0 and still the same warning message (and... no action ;) ).

**Comment by mbaklor** [comment]
Hi, I too installed 2.2.0 beta (whichever build was from today) and couldn't connect to the parameter with any of the types, and it worked from the ember+ viewer:
![image](https://user-images.githubusercontent.com/78748463/151702827-0555b470-acb2-4b69-a043-df1dc7f35ab9.png)

Any idea where the problem is? Maybe what was in the beta isn't your most recent build from here?

**Comment by baltedewit** [comment]
@mbaklor well, the "Int64" works fine with the Lawo software I can test with so I'm pretty sure it's not the parameter type itself that is the problem. If I can get access to the raw bytestream I can feed it into the decoder manually and probably figure out why it doesn't report to us as a known type. If you know how to send me a .pcap with just the ember+ traffic I"ll be happy to take a look at it.

**Comment by mbaklor** [comment]
A bit of light testing with wireshark later, it looks like only the first button press sends anything, and subsequent presses on any of the buttons I set up show up in the companion log but not in the wireshark. I'll send the capture as it is right now: a connection, one single correspondence and a bunch of keepalives, let me know if there's any more information you need.
[dhd-ember-capture.zip](https://github.com/bitfocus/companion-module-generic-emberplus/files/8104076/dhd-ember-capture.zip)

**Comment by baltedewit** [comment]
Thanks for sharing that, I can see what is wrong now. That node does not explicitly report its type as integer, instead it is inferred from the value. Support for this way of reporting types has been available in emberplus-connection for a while but I see companion is still using an older version that does not have this.

**Comment by mbaklor** [comment]
Update - everything works on my end with the latest release (2.2.0)
